# Generated by Django 2.1.7 on 2019-03-11 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEETINGS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(default=None, through='MEETINGS.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
