# Generated by Django 2.1.7 on 2019-03-12 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEETINGS', '0002_auto_20190311_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(default=None, related_name='user_meetings', through='MEETINGS.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
